# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
  language: en_core_web_md
  pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "RegexEntityExtractor"
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: True
  - name: "LexicalSyntacticFeaturizer"
  - name: "SpacyNLP"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100

  policies:
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
  - name: "RulePolicy"
  - name: "MappingPolicy"
  - name: "FormPolicy"
